### ISSUE TITLE
隐藏一下学号中间部分

### ISSUE THREAD

**Issue by suyuxuan** [GHY-ORG/AnswerMe2017#2]
![image](https://cloud.githubusercontent.com/assets/3740392/25093800/6a03b136-23c6-11e7-8069-073cfe1cbb42.png)

**Comment by SandBoat** [comment]
[修改 ShowTop10.js](https://github.com/GHY-ORG/AnswerMe2017/blob/6f92c5e499c5192154811ad198c88710cafbbbae/AnswerMe2017/script/showTop10.js)
